In [ ]:
import pandas as pd
import openpyxl


df = pd.read_excel("smileystatus.xlsx")

df.head()

,navnelbnr,cvrnr,pnr,brancheKode,branche,virksomhedstype,navn1,adresse1,postnr,By,...,naestseneste_kontrol_dato,tredjeseneste_kontrol,tredjeseneste_kontrol_dato,fjerdeseneste_kontrol,fjerdeseneste_kontrol_dato,URL,reklame_beskyttelse,Elite_Smiley,Geo_Lng,Geo_Lat
0,513605,34583730.0,1.017699e+09,DD.10.71.20,Specialforretning - Bager m.v.,Detail,Firdaws ApS,Enghavevej 172,2450,København SV,...,2024-02-07,1.0,2023-11-27,1.0,2023-11-15,http://www.findsmiley.dk/da-DK/Searching/Detai...,0,0,12.537889,55.656613
1,26029,18043041.0,1.001418e+09,DD.10.71.20,Specialforretning - Bager m.v.,Detail,KonditorBager,Dannebrogsgade 21,9700,Brønderslev,...,2021-12-09,2.0,2021-10-20,1.0,2019-09-24,http://www.findsmiley.dk/da-DK/Searching/Detai...,0,0,9.950767,57.270705
2,69750,21467782.0,1.004954e+09,DD.10.71.20,Specialforretning - Bager m.v.,Detail,NYTORVS BAGERI APS,Nytorv 1,7323,Give,...,2024-04-22,1.0,2023-10-06,1.0,2023-06-14,http://www.findsmiley.dk/da-DK/Searching/Detai...,0,0,9.237281,55.844766
3,555571,18623978.0,1.019633e+09,DD.10.71.20,Specialforretning - Bager m.v.,Detail,SuperBrugsen Havdrup Bageri,Møllemarken 6,4622,Havdrup,...,2024-12-17,1.0,2024-09-18,1.0,2024-04-04,http://www.findsmiley.dk/da-DK/Searching/Detai...,0,0,12.115530,55.543675
4,1292639,43771930.0,1.028920e+09,DD.10.71.20,Specialforretning - Bager m.v.,Detail,Digebageren,Storegade 20 stuen,6280,Højer,...,2024-11-27,1.0,2024-04-10,1.0,2023-12-20,http://www.findsmiley.dk/da-DK/Searching/Detai...,0,0,NaN,NaN

In [ ]:
import pandas as pd

df2 = df.rename(columns={
    "seneste_kontrol": "kontrol_1",
    "seneste_kontrol_dato": "dato_1",
    "naestseneste_kontrol": "kontrol_2",
    "naestseneste_kontrol_dato": "dato_2",
    "tredjeseneste_kontrol": "kontrol_3",
    "tredjeseneste_kontrol_dato": "dato_3",
    "fjerdeseneste_kontrol": "kontrol_4",
    "fjerdeseneste_kontrol_dato": "dato_4"
})

df_long = (
    pd.wide_to_long(
        df2,
        stubnames=["kontrol", "dato"],
        i="navnelbnr",
        j="tjek_nr",
        sep="_"
    )
    .reset_index()
)

df_long = df_long.dropna(subset=["kontrol", "dato"])
df_long["dato"] = pd.to_datetime(df_long["dato"])

,navnelbnr,tjek_nr,By,Elite_Smiley,Geo_Lat,Geo_Lng,URL,adresse1,branche,brancheKode,cvrnr,navn1,pnr,postnr,reklame_beskyttelse,virksomhedstype,kontrol,dato
0,513605,1,København SV,0,55.656613,12.537889,http://www.findsmiley.dk/da-DK/Searching/Detai...,Enghavevej 172,Specialforretning - Bager m.v.,DD.10.71.20,34583730.0,Firdaws ApS,1.017699e+09,2450,0,Detail,1.0,2024-09-27
1,26029,1,Brønderslev,0,57.270705,9.950767,http://www.findsmiley.dk/da-DK/Searching/Detai...,Dannebrogsgade 21,Specialforretning - Bager m.v.,DD.10.71.20,18043041.0,KonditorBager,1.001418e+09,9700,0,Detail,1.0,2022-05-03
2,69750,1,Give,0,55.844766,9.237281,http://www.findsmiley.dk/da-DK/Searching/Detai...,Nytorv 1,Specialforretning - Bager m.v.,DD.10.71.20,21467782.0,NYTORVS BAGERI APS,1.004954e+09,7323,0,Detail,1.0,2025-01-16
3,555571,1,Havdrup,0,55.543675,12.115530,http://www.findsmiley.dk/da-DK/Searching/Detai...,Møllemarken 6,Specialforretning - Bager m.v.,DD.10.71.20,18623978.0,SuperBrugsen Havdrup Bageri,1.019633e+09,4622,0,Detail,1.0,2025-04-08
4,1292639,1,Højer,0,NaN,NaN,http://www.findsmiley.dk/da-DK/Searching/Detai...,Storegade 20 stuen,Specialforretning - Bager m.v.,DD.10.71.20,43771930.0,Digebageren,1.028920e+09,6280,0,Detail,1.0,2025-01-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,1273360,1,Brønderslev,0,NaN,NaN,http://www.findsmiley.dk/da-DK/Searching/Detai...,Buurholtvej 11,Specialforretning - Bager m.v.,DD.10.71.20,37321060.0,Gl. Buurholt ApS,1.021003e+09,9700,0,Detail,1.0,2025-05-27
300,39531,1,Lemvig,0,56.548849,8.308479,http://www.findsmiley.dk/da-DK/Searching/Detai...,Konsul Andersens Gade 3,Specialforretning - Bager m.v.,DD.10.71.20,26259495.0,Kvickly Bager,1.003076e+09,7620,0,Detail,1.0,2025-05-22
301,28932,1,Herning,0,56.140192,8.961024,http://www.findsmiley.dk/da-DK/Searching/Detai...,Gl Landevej 143,Specialforretning - Bager m.v.,DD.10.71.20,12307136.0,Bager-Riget,1.000366e+09,7400,0,Detail,1.0,2026-01-16
302,966689,1,Viborg,0,56.448402,9.407487,http://www.findsmiley.dk/da-DK/Searching/Detai...,Fischers Plads 2,Specialforretning - Bager m.v.,DD.10.71.20,41905956.0,Café Simpel Surdej Studio,1.026541e+09,8800,0,Detail,1.0,2025-09-10
303,90217,1,Nykøbing F,0,54.759313,11.854141,http://www.findsmiley.dk/da-DK/Searching/Detai...,Guldborgsundcentret 23,Specialforretning - Bager m.v.,DD.10.71.20,35954716.0,føtex 1329 Bager,1.003225e+09,4800,0,Detail,1.0,2024-09-10

In [19]:
df_long["branche"].value_counts()

branche
Serveringsvirksomhed - Restauranter m.v.                        64674
Serveringsvirksomhed - Institutionskøkkener m.v.                30856
Dagligvareforretning uden/med begrænset behandling              26498
Serveringsvirksomhed - Uden behandling                           5980
Lager/lagerhotel og evt. engroshandel - Uden køl/frost           4802
Specialforretning - Delikatesse, specialiteter m.v. med beha     4536
Specialforretning - Bager m.v.                                   3820
Kontorvirksomhed eller agenturvirksomhed - uden lager            3761
Specialforretning - Slagter m.v.                                 3621
Transportvirksomhed, engros                                      2595
Markedsføring af fødevarekontaktmaterialer, engros               2580
Fremstilling af fødevarekontaktmaterialer, engros                2454
Fremstilling af vegetabilske produkter mv. evt. med indhold      1831
Catering med levering til detailvirksomheder (detail med eng     1495
Lager/lagerhotel og evt. engroshandel - Med køl/frost            1480
Specialforretning - Fisk m.v.                                    1140
Fremstilling af drikkevarer m.v.                                  914
Fremstilling af animalske produkter - Fisk og muslinger m.v.      800
Lager og evt. engroshandel med salg til detailvirksomheder (      706
Fremstilling af animalske produkter - Kød                         540
Fremstilling af animalske produkter - Mælk og ost                 386
Fremstilling af kosttilskud, tilsætningsstoffer m.v.              385
Markedsføring af fødevarekontaktmaterialer, detail                329
Slagterier                                                        314
Fremstilling af fødevarekontaktmaterialer, detail                 306
Virksomhed, foreløbig: Detailforr. m. beh., fx mikrobryggeri      194
Frysehuse med indfrysning af animalske produkter                  113
Kædekontrolhovedkontor - Fødevarer                                 85
Fremstilling af animalske produkter - Andre produkter              64
Slagtebusser                                                       62
Virksomhed, foreløbig: Engroshandel og/eller lager/lagerhote       44
Transportvirksomhed, detail                                        42
Virksomhed, foreløbig: Internethandel, udelukkende salg og m       39
Virksomhed, foreløbig: Butikshandel, fx kiosk, apotek, helse       25
Virksomhed, foreløbig: Restaurant, pizzeria, cafe, kantine,        23
Fremstilling af animalske produkter - Æg                           20
Håndtering af levende toskallede bløddyr                           16
Kvindemælkscentraler (detail med engros)                           12
Virksomhed, foreløbig: Fremstill. af fødevarekontaktmaterial        6
Virksomhed, foreløbig: Institutionskøkken, fx børneinstituti        6
Virksomhed, foreløbig: Mobil virksomh.(fx salg af br. mandl.        6
Virksomhed, foreløbig: Butikshandel, fx dagligvareforr., grø        5
Virksomhed, foreløbig: Fremstill. af bagværk, brød, pasta o.        4
Virksomhed, foreløbig: Fremstill./pakn. af drikkev., maltfab        4
Virksomhed, foreløbig: Smørrebrødsforr., delikatesseafd., ta        4
Virksomhed, foreløbig: Servering, fx værtshus, vinbar, autom        3
Virksomhed, foreløbig: Slagter, slagterafdeling                     3
Virksomhed, foreløbig: Kontorvirksomhed (fødevarer og/eller         2
Virksomhed, foreløbig: Transportvirksomhed, engros                  2
Virksomhed, foreløbig: Fremstill./pakn. af konfekture, sukke        2
Virksomhed, foreløbig: Fremstill./pakn. af tils.stoff., kost        1
Virksomhed, foreløbig AUT: Slagteri, slagteri med fremstilli        1
Virksomhed, foreløbig AUT: Fremstill./pakn. primært ud fra m        1
Virksomhed, foreløbig: Bagerforretning, bagerafdeling, kondi        1
Name: count, dtype: int64

In [22]:
df_long["By"].value_counts().head(20)

By
København K      5229
København V      3631
København S      3483
Århus C          3408
København Ø      2782
Aalborg          2619
København N      2538
Odense C         2261
Roskilde         2225
Vejle            2036
Kolding          2011
Frederiksberg    1915
Horsens          1733
Silkeborg        1663
Herning          1640
Hillerød         1523
Viborg           1518
Valby            1452
København NV     1432
Hvidovre         1412
Name: count, dtype: int64

In [24]:
df_long["dato"] = pd.to_datetime(df_long["dato"])

df_long.groupby(df_long["dato"].dt.year)["kontrol"].mean()

dato
2003    1.000000
2004    1.146341
2005    1.089655
2006    1.064935
2007    1.060811
2008    1.028340
2009    1.023952
2010    1.026946
2011    1.045147
2012    1.036176
2013    1.059730
2014    1.038380
2015    1.041424
2016    1.023507
2017    1.026653
2018    1.035010
2019    1.040000
2020    1.032438
2021    1.043300
2022    1.049136
2023    1.067205
2024    1.114922
2025    1.192092
2026    1.240839
Name: kontrol, dtype: float64

In [25]:
df_long.groupby("branche")["kontrol"].mean().sort_values()

branche
Virksomhed, foreløbig: Slagter, slagterafdeling                 1.000000
Virksomhed, foreløbig: Mobil virksomh.(fx salg af br. mandl.    1.000000
Virksomhed, foreløbig: Institutionskøkken, fx børneinstituti    1.000000
Virksomhed, foreløbig: Fremstill./pakn. af drikkev., maltfab    1.000000
Virksomhed, foreløbig: Bagerforretning, bagerafdeling, kondi    1.000000
Virksomhed, foreløbig AUT: Slagteri, slagteri med fremstilli    1.000000
Virksomhed, foreløbig: Smørrebrødsforr., delikatesseafd., ta    1.000000
Kvindemælkscentraler (detail med engros)                        1.000000
Håndtering af levende toskallede bløddyr                        1.000000
Fremstilling af fødevarekontaktmaterialer, engros               1.023227
Slagterier                                                      1.038217
Catering med levering til detailvirksomheder (detail med eng    1.049498
Lager og evt. engroshandel med salg til detailvirksomheder (    1.056657
Fremstilling af fødevarekontaktmaterialer, detail               1.065359
Fremstilling af drikkevarer m.v.                                1.067834
Kædekontrolhovedkontor - Fødevarer                              1.070588
Serveringsvirksomhed - Institutionskøkkener m.v.                1.075058
Transportvirksomhed, engros                                     1.076301
Fremstilling af animalske produkter - Andre produkter           1.078125
Specialforretning - Fisk m.v.                                   1.083333
Specialforretning - Slagter m.v.                                1.084783
Markedsføring af fødevarekontaktmaterialer, engros              1.086047
Frysehuse med indfrysning af animalske produkter                1.088496
Lager/lagerhotel og evt. engroshandel - Uden køl/frost          1.092670
Specialforretning - Delikatesse, specialiteter m.v. med beha    1.097002
Fremstilling af animalske produkter - Æg                        1.100000
Lager/lagerhotel og evt. engroshandel - Med køl/frost           1.100000
Kontorvirksomhed eller agenturvirksomhed - uden lager           1.100239
Fremstilling af animalske produkter - Fisk og muslinger m.v.    1.106250
Fremstilling af kosttilskud, tilsætningsstoffer m.v.            1.109091
Fremstilling af vegetabilske produkter mv. evt. med indhold     1.111415
Slagtebusser                                                    1.112903
Serveringsvirksomhed - Restauranter m.v.                        1.118378
Transportvirksomhed, detail                                     1.119048
Dagligvareforretning uden/med begrænset behandling              1.124387
Fremstilling af animalske produkter - Kød                       1.137037
Serveringsvirksomhed - Uden behandling                          1.143311
Fremstilling af animalske produkter - Mælk og ost               1.147668
Specialforretning - Bager m.v.                                  1.148953
Markedsføring af fødevarekontaktmaterialer, detail              1.170213
Virksomhed, foreløbig: Restaurant, pizzeria, cafe, kantine,     1.217391
Virksomhed, foreløbig: Butikshandel, fx kiosk, apotek, helse    1.280000
Virksomhed, foreløbig: Transportvirksomhed, engros              1.500000
Virksomhed, foreløbig: Detailforr. m. beh., fx mikrobryggeri    1.556701
Virksomhed, foreløbig: Butikshandel, fx dagligvareforr., grø    1.600000
Virksomhed, foreløbig: Servering, fx værtshus, vinbar, autom    1.666667
Virksomhed, foreløbig: Fremstill. af fødevarekontaktmaterial    1.833333
Virksomhed, foreløbig: Internethandel, udelukkende salg og m    1.871795
Virksomhed, foreløbig: Kontorvirksomhed (fødevarer og/eller     2.000000
Virksomhed, foreløbig: Engroshandel og/eller lager/lagerhote    2.068182
Virksomhed, foreløbig: Fremstill./pakn. af konfekture, sukke    2.500000
Virksomhed, foreløbig: Fremstill. af bagværk, brød, pasta o.    3.500000
Virksomhed, foreløbig: Fremstill./pakn. af tils.stoff., kost    4.000000
Virksomhed, foreløbig AUT: Fremstill./pakn. primært ud fra m    4.000000
Name: kontrol, dtype: float64

In [27]:
df_long.groupby("By")["kontrol"].mean().sort_values(ascending=False).head(10)

By
Havndal         1.292683
Bevtoft         1.285714
Vandel          1.285714
Torrig L        1.275862
Åbyhøj          1.273859
Gandrup         1.272727
Bylderup Bov    1.250000
Tranbjerg J     1.250000
Tylstrup        1.232558
Brabrand        1.222764
Name: kontrol, dtype: float64